- name: Run PostgreSQL container
  docker_container:
    name: mydb
    image: postgres:13
    env:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    networks:
      - name: app-network
    state: started
    restart_policy: always
