name: CI devops 2025

on:
  push:
    branches:
      - main
      - develop # Launch on pushes to main and develop branches
  pull_request: # Also launch on pull requests to main and develop (good practice)
    branches:
      - main
      - develop

jobs:
  test-backend:
    runs-on: ubuntu-24.04 # Using the specified Ubuntu version
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Fetches your repository code

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21' # Specifies JDK version 21
          distribution: 'temurin' # Specifies the Java distribution (Temurin is a popular choice)

      - name: Build and test with Maven
        run: mvn clean verify --file ./simple-api/pom.xml # Runs the Maven command.
                                                        # Assuming your simple-api is in a subfolder.
                                                        # If pom.xml is in the root, remove "--file ./simple-api/pom.xml"
                                                        # and just use "mvn clean verify"
                                                        # ... (name, on, and test-backend job remain the same) ...
                                                        
  build-and-push-docker-image:
    needs: test-backend # Ensures this job runs only if 'test-backend' succeeds
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./simple-api # Path to the Dockerfile for the backend (adjust if needed)
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest
          push: ${{ github.ref == 'refs/heads/main' }} # Push only if on the main branch

      - name: Build and push database image
        uses: docker/build-push-action@v6
        with:
          context: ./database # Path to the Dockerfile for the database (adjust if needed)
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest # Choose an appropriate name
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build and push httpd image
        uses: docker/build-push-action@v6
        with:
          context: ./httpd # Path to the Dockerfile for httpd (adjust if needed)
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest # Choose an appropriate name
          push: ${{ github.ref == 'refs/heads/main' }}