name: CI devops 2025

on:
  push:
    branches:
      - main
      - develop # Launch on pushes to main and develop branches
  pull_request: # Also launch on pull requests to main and develop (good practice)
    branches:
      - main
      - develop

jobs:
  test-backend:
    runs-on: ubuntu-24.04 # Using the specified Ubuntu version
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Fetches your repository code

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21' # Specifies JDK version 21
          distribution: 'temurin' # Specifies the Java distribution (Temurin is a popular choice)

      - name: Build and test with Maven
        run: mvn clean verify --file ./simple-api/pom.xml # Runs the Maven command.

  build-and-push-docker-image:
    if: github.ref == 'refs/heads/main' # This job only runs on main
    needs: test-backend # Ensures this job runs only if 'test-backend' succeeds
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./simple-api
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest
          push: true

      - name: Build and push database image
        uses: docker/build-push-action@v6
        with:
          context: ./database
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest
          push: true

      - name: Build and push httpd image
        uses: docker/build-push-action@v6
        with:
          context: ./http-server
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest
          push: true
